# Day 4 - Pandas Basics

**AI & Machine Learning Internship**

**Author:** Neethu Suresh

## Topics Covered

- Introduction to Pandas
- Series
- DataFrame
- Reading Data
- Data Inspection
- Selecting Data
- Basic Statistics

In [2]:
import pandas as pd

## Creating a Pandas Series

In [3]:
marks = pd.Series([85, 90, 78, 92, 88])

print(marks)

0    85
1    90
2    78
3    92
4    88
dtype: int64

## Creating a DataFrame

In [4]:
data = {
    "Name": ["Anu", "Rahul", "Sneha", "Arjun", "Meera"],
    "Age": [20, 21, 19, 22, 20],
    "Marks": [85, 90, 78, 92, 88]
}

df = pd.DataFrame(data)

df

    Name  Age  Marks
0    Anu   20     85
1  Rahul   21     90
2  Sneha   19     78
3  Arjun   22     92
4  Meera   20     88

## Display First and Last Records

In [5]:
print("First Three Rows")
display(df.head(3))

print("Last Two Rows")
display(df.tail(2))

First Three Rows

    Name  Age  Marks
0    Anu   20     85
1  Rahul   21     90
2  Sneha   19     78

Last Two Rows

    Name  Age  Marks
3  Arjun   22     92
4  Meera   20     88

## Data Information

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Age     5 non-null      int64
 2   Marks   5 non-null      int64
dtypes: int64(2), str(1)
memory usage: 252.0 bytes

## Statistical Summary

In [7]:
df.describe()

             Age      Marks
count   5.000000   5.000000
mean   20.400000  86.600000
std     1.140175   5.458938
min    19.000000  78.000000
25%    20.000000  85.000000
50%    20.000000  88.000000
75%    21.000000  90.000000
max    22.000000  92.000000

## Selecting Columns

In [8]:
df["Name"]

0      Anu
1    Rahul
2    Sneha
3    Arjun
4    Meera
Name: Name, dtype: str

In [9]:
df[["Name", "Marks"]]

    Name  Marks
0    Anu     85
1  Rahul     90
2  Sneha     78
3  Arjun     92
4  Meera     88

## Filtering Data

In [10]:
df[df["Marks"] > 85]

    Name  Age  Marks
1  Rahul   21     90
3  Arjun   22     92
4  Meera   20     88

## Adding a New Column

In [11]:
df["Result"] = ["Pass", "Pass", "Pass", "Pass", "Pass"]

df

    Name  Age  Marks Result
0    Anu   20     85   Pass
1  Rahul   21     90   Pass
2  Sneha   19     78   Pass
3  Arjun   22     92   Pass
4  Meera   20     88   Pass

## Basic Statistics

In [12]:
print("Average Marks:", df["Marks"].mean())
print("Highest Marks:", df["Marks"].max())
print("Lowest Marks:", df["Marks"].min())

Average Marks: 86.6
Highest Marks: 92
Lowest Marks: 78

## Conclusion

Pandas makes it easy to organize, analyze, and manipulate structured data. It is one of the most important libraries used in Data Science and Machine Learning.